services:
  - type: web
    name: novust-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: NOVUST_MODEL
        value: gpt-4o-mini
      # Only needed if you add the disk block below:
      - key: DATA_DIR
        value: /var/data
    healthCheckPath: /health
    autoDeploy: true

    # OPTIONAL: persistent SQLite across deploys/restarts
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
