services:
  - type: web
    name: novust-api
    env: node
    autoDeploy: true
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false            # set in Render dashboard
      - key: NOVUST_MODEL
        value: gpt-5-thinking
      - key: NOVUST_JWT_SECRET
        sync: false            # set in Render dashboard
      - key: ALLOW_ORIGINS
        value: "https://<your-netlify-domain>,http://localhost:3000"
      - key: DATA_DIR
        value: /opt/render/project/src/data
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
