# render.yaml — Novust API (Node + SQLite on Render)
services:
  - type: web
    name: novust-api
    env: node
    plan: free

    buildCommand: npm install
    startCommand: node server.js

    # Health check
    healthCheckPath: /health

    # Auto deploy on push to the linked branch
    autoDeploy: true

    # Environment variables (secrets managed in dashboard)
    # `sync: false` = keep values from the Render dashboard; do not overwrite from YAML.
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: FORCE_OPENAI_API_KEY
        sync: false
      - key: NOVUST_MODEL
        value: gpt-4o-mini
      - key: DATA_DIR
        value: /var/data
      - key: NODE_ENV
        value: production

    # OPTIONAL: persistent disk for SQLite (keeps DBs across restarts)
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
